ALTER TABLE "ProductImage" ADD COLUMN "cardCropX" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "ProductImage" ADD COLUMN "cardCropY" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "ProductImage" ADD COLUMN "cardCropZoom" DOUBLE PRECISION NOT NULL DEFAULT 1;
ALTER TABLE "ProductImage" ADD COLUMN "cardCropAspectRatio" DOUBLE PRECISION NOT NULL DEFAULT 0.75;
ALTER TABLE "ProductImage" ADD COLUMN "cardCropAreaX" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "ProductImage" ADD COLUMN "cardCropAreaY" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "ProductImage" ADD COLUMN "cardCropAreaWidth" DOUBLE PRECISION NOT NULL DEFAULT 100;
ALTER TABLE "ProductImage" ADD COLUMN "cardCropAreaHeight" DOUBLE PRECISION NOT NULL DEFAULT 100;
