ALTER TABLE "Specialty" ADD COLUMN "previewImageCropX" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Specialty" ADD COLUMN "previewImageCropY" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Specialty" ADD COLUMN "previewImageZoom" DOUBLE PRECISION NOT NULL DEFAULT 1;
ALTER TABLE "Specialty" ADD COLUMN "previewImageAspectRatio" DOUBLE PRECISION NOT NULL DEFAULT 0.8;
ALTER TABLE "Specialty" ADD COLUMN "cardImageCropX" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Specialty" ADD COLUMN "cardImageCropY" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Specialty" ADD COLUMN "cardImageZoom" DOUBLE PRECISION NOT NULL DEFAULT 1;
ALTER TABLE "Specialty" ADD COLUMN "cardImageAspectRatio" DOUBLE PRECISION NOT NULL DEFAULT 1.3333333333333333;
