ALTER TYPE "HomepageContentBlockKey" ADD VALUE IF NOT EXISTS 'HERO_FEATURE_BAR';
ALTER TYPE "HomepageContentBlockKey" ADD VALUE IF NOT EXISTS 'CATEGORY_GRID';
ALTER TYPE "HomepageContentBlockKey" ADD VALUE IF NOT EXISTS 'FEATURED_SLIDER';
ALTER TYPE "HomepageContentBlockKey" ADD VALUE IF NOT EXISTS 'NEWSLETTER';

ALTER TABLE "HomepageContentBlock" ADD COLUMN IF NOT EXISTS "metadata" JSONB;
ALTER TABLE "HomepagePromoTile" ADD COLUMN IF NOT EXISTS "isNew" BOOLEAN NOT NULL DEFAULT false;
